spring:
  application:
    name: mybatis-plus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 20030304
    url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
# mybatis-plus日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台输出日志
  mapper-locations: classpath:mapper/*.xml #配置mapper.xml文件位置
  global-config: #全局配置,设置主键自增的模式
    db-config:
      id-type: auto
